declare global {
  namespace NodeJS {
    interface ProcessEnv {
      PORT: string,
      ENVIRONMENT: string,
      DATABASE_URL: string,
      DATABASE_CONNECTION_POOL_SIZE: string,
      WEB_URL: string,
      REDIS_SECRET: string,
      MIDTRANS_SERVER_KEY: string,
      MIDTRANS_APP_URL: string,
      REDIS_URL: string,
      DOMAIN: string,
      AWS_ACCESS_KEY: string,
      AWS_SECRET_ACCESS_KEY: string,
      AWS_SPACE_ACCESS_KEY: string,
      AWS_SPACE_SECRET_ACCESS_KEY: string,
      AWS_BUCKET_SPACE: string,
      AWS_SPACE_ENDPOINT: string,
      AWS_BUCKET: string,
      NODE_ENV: string,
      CA_CERT: string,
      EMAIL_SMPT_HOST: string,
      EMAIL_SMPT_PORT: string,
      EMAIL_USER: string,
      EMAIL_PASSWORD: string,
      EMAIL_NOTIFICATION: string,
      LANDING_PAGE_WEB_URL: string,
      APM_SERVICE_URL: string,
      XENDIT_SECRET_KEY: string,
      ASK_QUESTION_RECIPIENT_EMAIL: string,
      TYPEORM_LOGGING: string,
      XENDIT_VERIF_TOKEN: string,
      RECAPTCHA_SECRET_KEY: string,
      RSA_PRIVATE_KEY: string,
      RSA_PUBLIC_KEY: string,
      AES_SECRET: string,
      GOOGLE_CLIENT_ID: string,
      GOOGLE_CLIENT_SECRET: string,
      LINKEDIN_CLIENT_ID: string,
      LINKEDIN_CLIENT_SECRET: string,
      LINKEDIN_API_URL: string,
      LINKEDIN_OAUTH_URL: string,
      GOOGLE_ADMIN_TOKEN: string,
      DATABASE_ANALYTICS_URL: string,
      DATABASE_CONNECTION_POOL_SIZE_ANALYTICS: string,
      RUN_ANALYTICS: string,
      PIXEL_ACCESS_TOKEN?: string,
      PIXEL_ID?: string,
      DBB_INSTAGRAM_ID?: string,
      FACEBOOK_APP_ID?: string,
      FACEBOOK_APP_SECRET?: string,
      LEARNING_CENTER_URL: string,
      NEW_LANDING_PAGE_URL: string,
      DIBIMBING_FORM_URL: string,
      STORAGE_CLIENT_EMAIL: string,
      STORAGE_PRIVATE_KEY: string,
      STORAGE_PROJECT_ID: string,
      JOBS_URL: string,
      AFFILIATE_URL: string,
      ADMIN_URL: string,
      SUBSEMAIL_FORMID: number,
      CAKRAWALA_URL: string,
      REGISTER_CAKRAWALA_URL: string,
      CAKRAWALA_EMAIL_SMPT_HOST: string,
      CAKRAWALA_EMAIL_SMPT_PORT: string,
      CAKRAWALA_EMAIL_USER: string,
      CAKRAWALA_EMAIL_PASSWORD: string
    }
  }
}

export {}